# Dockerfile.batch
FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

EXPOSE 8001

CMD ["uvicorn", "batch_server:app", "--host", "0.0.0.0", "--port", "8001"]
